### ISSUE TITLE
Crash when getting on horses

### ISSUE THREAD

**Issue by PixelatedBruh** [RobertSkalko/Age-of-Exile#1]
When trying to get on a horse the game closes and this is my crash log.

Time: 7/24/20 6:38 PM
Description: Unexpected error

org.spongepowered.asm.mixin.injection.callback.CancellationException: The call method_1744 is not cancellable.
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfo.cancel(CallbackInfo.java:101)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.setReturnValue(CallbackInfoReturnable.java:106)
	at net.minecraft.class_329.handler$bnd000$on$getMaxHealth(class_329.java:5329)
	at net.minecraft.class_329.method_1744(class_329.java:772)
	at net.minecraft.class_329.method_1741(class_329.java:960)
	at net.minecraft.class_329.method_1753(class_329.java:216)
	at net.minecraft.class_757.method_3192(class_757.java:584)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfo.cancel(CallbackInfo.java:101)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.setReturnValue(CallbackInfoReturnable.java:106)
	at net.minecraft.class_329.handler$bnd000$on$getMaxHealth(class_329.java:5329)
	at net.minecraft.class_329.method_1744(class_329.java:772)
	at net.minecraft.class_329.method_1741(class_329.java:960)
	at net.minecraft.class_329.method_1753(class_329.java:216)

-- Affected level --
Details:
	All players: 1 total; [class_746['Fort_Chungus'/3, l='ClientLevel', x=230.14, y=4.97, z=-66.04]]
	Chunk stats: SodiumChunkCache: 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (224,4,-64), Chunk: (at 0,0,0 in 14,-4; contains blocks 224,0,-64 to 239,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 170 game time, 170 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2181)
	at net.minecraft.class_310.method_1514(class_310.java:677)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 962686064 bytes (918 MB) / 3467116544 bytes (3306 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G
	Fabric Mods: 
		adabraniummod: Adabranium Mod 1.1.5.1
		adorn: Adorn 1.9.1+1.16.1
		adventurez: AdventureZ 1.0.6
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		bettergraves: Better Graves 0.3.0
		betternether: Better Nether 3.5.0
		blast: BLAST 1.3.2
		blockus: Blockus 1.6.2
		blue_endless_jankson: jankson 1.2.0
		bookworm: Bookworm Library 3.0.1
		bucket-hat: Bucket Hat 1.0.2
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		byg: BYG 1.0.10
		cardinal-components: Cardinal Components API 2.4.2
		cardinal-components-base: Cardinal Components API (base) 2.4.2
		cardinal-components-block: Cardinal Components API (blocks) 2.4.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.4.2
		cardinal-components-entity: Cardinal Components API (entities) 2.4.2
		cardinal-components-item: Cardinal Components API (items) 2.4.2
		cardinal-components-level: Cardinal Components API (world saves) 2.4.2
		cardinal-components-util: Cardinal Components API (utilities) 2.4.2
		cardinal-components-world: Cardinal Components API (worlds) 2.4.2
		cavebiomes: Cave Biomes 0.2.3
		chainmail: Chainmail 0.3.0
		chatemotes: ChatEmotes 1.1
		cinderscapes: Cinderscapes 1.0.5+build.36-1.16.1
		cleancut: CleanCut mc1.16-2.1-fabric
		clear-skies: Clear Skies 1.3.38
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cotton: Cotton 1.0.5
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.5
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		creativebuttonmover: Creative Button Mover 0.2.5
		curios: Curios API 1.16.1-0.2
		dark-loading-screen: Dark Loading Screen 1.3.2
		dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
		endreborn: End: Rebellion 1.5
		expandedstorage: ExpandedStorage 5.3.16
		fabric: Fabric API 0.16.0+build.384-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f7c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-furnaces: Fabric Furnaces 1.3.1-1.16.1
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		fatxporbs: Fat Experience Orbs 0.0.7
		fiber: fiber 0.23.0-1
		gbfabrictools: GBfabrictools 1.2.2+1.16
		golemsgalore: Golems Galore 0.1.4+mc.1.16.1
		grindenchantments: Grind Enchantments 1.1.1+1.16.1
		houraielixir: Hourai Elixir r3
		inmis: Inmis 1.2.0-1.16.1
		jankson: Jankson 3.0.0+j1.2.0
		kirin: Kirin UI 1.6.4-1.16-rc1-1.16-SNAPSHOT
		koi: Koi Fish 1.0.2
		lambdynlights: LambDynamicLights 1.2.2+1.16.1
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libcd: LibCapableData 2.5.0+1.16.1
		libgui: LibGui 2.0.1+1.16.1
		libstructure: Libstructure 1.3
		litematica: Litematica 0.0.0-dev.20200630.022912
		lithium: Lithium 0.5.1
		maelstrom_library: Maelstrom Library 0.4
		magna: Magna 1.1.2-1.16.1
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		mighty_mangoes: Mighty Mangoes 1.0.0
		minecraft: Minecraft 1.16.1
		mmorpg: Age of Exile 1.0.1
		mo_glass: Mo Glass 1.3-MC1.16.1
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2-1.16.1
		mobz: MobZ 2.4.2
		modmenu: Mod Menu 1.12.2+build.17
		moenchantments: Mo'Enchantments 1.12.4-beta2
		mooblooms: Mooblooms 1.3.1
		more_gems: More Gems 1.0.44
		moreberries: More Berries 1.3.1
		ninjaphenix-container-lib: NinjaPhenix's Container Library 1.1.5
		org_aeonbits_owner_owner: owner 1.0.12
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		origins: Origins 1.16-0.2.5
		overloadedarmorbar: Overloaded Armor Bar 5.0.0-fabric
		parchment: Parchment 1.0.2+1.15.2
		phosphor: Phosphor 0.6.0+build.7
		piglintag: PiglinTag 1.0.0
		pigpoop: Pig Poop 1.1.3
		platos: Plato's Transporters 1.3.1.1
		playerabilitylib: Pal 1.2.0
		presencefootsteps: Presence Footsteps r26+1.16-rc1
		rare-ice: Rare Ice 0.2.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.3.1
		ringsofascension: Rings of Ascension 1.0.3
		riverredux: River Redux 0.1.4
		rotten: FleshZ 1.2.2
		roughlyenoughitems: Roughly Enough Items 4.10.2
		shapes: Shapes 2.0.0+build.10
		shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
		simplyplatinum: Simply Platinum 2.0.0
		sodium: Sodium 0.1.0
		spinnery: Spinnery 3.0.48
		spruceui: SpruceUI 1.5.8
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		structurized: Structurized 1.0.0
		stuffz: StuffZ 2.2.2
		terraform: Terraform 2.1.7+build.31
		terrestria: Terrestria 2.0.4+build.50
		traverse: Traverse 2.2.14+build.28
		trinkets: Trinkets 2.6.2
		trumpet-skeleton: Trumpet Skeleton 1.1.2
		universalcomponents: Universal Components 0.7.2+1.16-pre2
		vanilla-hammers: Vanilla Hammers 1.10.1-1.16.1
		vanillaexcavators: Vanilla Excavators 1.1.0
		voxelmap: VoxelMap 1.10.6
		walljump: Wall-Jump! 1.3.3+1.16.1
		wildworld: Wild World 1.2.3-1.16
		window_title_changer: Window Title Changer 2.0.0-1.16.1
		winged: Winged Mod 1.16-1.2
		wolveswitharmor: Wolves With Armor 1.4.0-1.16.1
		worldedit: WorldEdit 7.2.0-beta-01+0eb9ac7
		wurst: Wurst Client v7.4-MC1.16.1
		zmod: AppleZ 1.9.0
	Launched Version: fabric-loader-0.9.0+build.204-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.48, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Randy's Music Disc Pack V3.zip, file/Sildurs fabulous shaders v1.0.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz

**Comment by RobertSkalko** [comment]
Fixed de7a54f5c685eec09d042f3251e04171349f6062
