### ISSUE TITLE
Server crashes with version 1.16.2-1.1.0

### ISSUE THREAD

**Issue by Nourio** [RobertSkalko/Age-of-Exile#10]
Fresh server is crashing with an error of

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mmorpg'!
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientChunkEvents in environment type SERVER

It doesn't seem to be generating any crash reports for some reason. If you need any more information just let me know.

**Comment by RobertSkalko** [comment]
Woops, I'll push a quick hotfix

**Comment by Nourio** [comment]
Thanks for the quick reply. Updated it to 1.1.1 and now the server launches but it's crashing when I join the server with another error

java.lang.NoClassDefFoundError: net/minecraft/class_746
	at com.robertx22.age_of_exile.areas.AreaData.lambda$getLevelRange$0(AreaData.java:53) ~[Age-Of-Exile-1.16.2-1.1.1.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746

**Comment by RobertSkalko** [comment]
Just woke up, pushed another hotfix.

**Comment by Nourio** [comment]
Thanks, it fixed the crash and I was able to play, but I'm experiencing another issue where my client gets kicked while "ENABLE_FOOD_EFFECTS" and "ENABLE_AUTO_FOOD_COMPATIBILITY" are enabled and I eat something.

**Comment by RobertSkalko** [comment]
Can he give a log?

**Comment by RobertSkalko** [comment]
Nvm i think i found the problem

**Comment by Nourio** [comment]
It works great now, thanks for the speedy fix.
