### ISSUE TITLE
Blocking with shield while bow is out and Using Produce arrows

### ISSUE THREAD

**Issue by EanLoss** [RobertSkalko/Age-of-Exile#100]
Blocking with shield while bow is out and using produce arrows places produce arrows on cooldown and yields no arrows

**Comment by RobertSkalko** [comment]
Cancelling a spell by blocking or attacking while it's being casted will cancel and put it on cooldown, yes. I might later try tweak it so it doesn't put on cooldown, but this isn't a bug so closing.
