### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by AlterDragon** [RobertSkalko/Age-of-Exile#108]
It crash after i choose a talent and about gem.
[crash-2021-06-10_17.36.59-client.txt](https://github.com/RobertSkalko/Age-of-Exile/files/6630150/crash-2021-06-10_17.36.59-client.txt)

**Comment by RobertSkalko** [comment]
does that happen when you remove my mod?

**Comment by AlterDragon** [comment]
Nope, it crash after i choose a talent from talent tree
