### ISSUE TITLE
World of Exile makes the game freeze when creating a new world, on latest Fabric API.

### ISSUE THREAD

**Issue by githubbingitup** [RobertSkalko/Age-of-Exile#111]
World-Of-Exile-1.16.5-1.2.2.jar
Fabric-api-0.35.1+ 1.16.jar

It works with 0.35.0 instead so if anyone else runs into this issue, just downgrade Fabric API for the time being.

**Comment by RobertSkalko** [comment]
Hm, they removed their BiomeAccessor mixin i see. Really weird why they change stuff on a stable version..

**Comment by RobertSkalko** [comment]
I pushed a new version for world of exile on curseforge (dungeons of exile named currently). Try downloading that and check. It should use the new version when there's 2 mods. I'll update it to AOE too these days

**Comment by githubbingitup** [comment]
this problem is fixed in all the latest versions
