### ISSUE TITLE
MMORPG Dimension Teleporter Bugged Out

### ISSUE THREAD

**Issue by githubbingitup** [RobertSkalko/Age-of-Exile#112]
Note: this only happened when creating the teleporter on a team. testing it solo in singleplayer, I did not have this issue.

When trying to teleport into the dungeon, it says "There was a teleport bug but the auto correction system should have teleported you back correctly" and it sends me back to my bed. After breaking the actual teleporter, the purple portal blocks didn't disappear and could not be removed in creative either. Trying to use a new key and shards to generate another dungeon makes the portal blocks reset, but no change to the glitch.

**Comment by RobertSkalko** [comment]
The purple portal blocks can be mined in survival, not to mention creative?

I'm not sure why the teleport didn't work though. Can you describe what you did?

**Comment by githubbingitup** [comment]
Ok, I was able to mine them with a pickaxe - I just couldn't delete them in creative so I thought it was an issue.

I used the command to create a team, then spawned the portal, keys, and shards in creative. I use the key on it, then click the center spot and select a dungeon. The portal blocks appeared for me and my friend and when going on them, it gave us that message and put us to spawn.

I've tried re-creating it and it never works and always generates 2 portals even when I hit solo dungeon.

**Comment by RobertSkalko** [comment]
What's your mod version?

**Comment by RobertSkalko** [comment]
Also it should always create 4 portals if there's space around it.

**Comment by githubbingitup** [comment]
2.09 and the only mods I have are the required files for Age of Exile like Curios and Library of Exile. All the most recent versions.

It only created 2 portals for me.

**Comment by RobertSkalko** [comment]
Give me a log still, maybe there's errors there

**Comment by githubbingitup** [comment]
sorry, this was a mistake on my part. I thought I had cleaned out my mods, but I still had in Drogtor Nicknames mod.

Setting a custom nickname to your player prevents you from entering the dimensions from this mod. I'm not sure if that's an issue with how this mod uses dimensions or an issue with his nickname mod. I don't get the problem with Aether, but its not a big deal to not have player nicknames.

**Comment by RobertSkalko** [comment]
This is so weird. I'll take a look at that mod later. Thanks for telling me! Closing. 

You can tell them about this bug btw if you want.

**Comment by githubbingitup** [comment]
no prob, I reported it on their page too!

**Comment by RobertSkalko** [comment]
I'll push a fix, try with Library-Of-Exile-1.16.5-1.0.12.jar.

Turned out it was on my end.
