### ISSUE TITLE
World of Exile - some dungeon types not generating.

### ISSUE THREAD

**Issue by githubbingitup** [RobertSkalko/Age-of-Exile#113]
I've noticed this for a while now. I can use /locate to find ladder and brick towers (both look the same on the outside) but I cannot find Blackstone towers or Jigsaw dungeons with it. Flying around exploring I can't find them anywhere either, both above or underground.

**Comment by RobertSkalko** [comment]
Because they only spawn in hell dimension

**Comment by githubbingitup** [comment]
ok thx!
