### ISSUE TITLE
Dexterity and Strength Stats not showing proper Armor and Dodge Rating Percentage

### ISSUE THREAD

**Issue by iantato** [RobertSkalko/Age-of-Exile#117]
Upping Dexterity and Strength actually doesn't increase the Dodge Rating or Armor in the stat hub

**Comment by RobertSkalko** [comment]
Do you actually have any armor or dodge? Like when you look at the stat, is it above 0?

**Comment by iantato** [comment]
oh i see alr then I guess I was wrong to what it does
