### ISSUE TITLE
Breath gem(s) not hitting right

### ISSUE THREAD

**Issue by kiomadoushi** [RobertSkalko/Age-of-Exile#118]
1.16.5-2.0.12
The Fire Breath Gem only ever hits once on any single enemy. For its low damage and constant stream of fire, it really seems it should be hitting multiple times. Instead, it hits enemies as expected for a fire breath, and then per each enemy hit, they become immune to further hits from it.

Even if you tap only once and try to stagger it, they don't take damage again.

**Comment by Demiosis** [comment]
Similarly to koimadoushi, Frost breath seem to work properly with Age of exile mobs : small golems, magus but it only hit minecraft and other mod's creatures once then stop working..  V 1.16.5-2.0.12

**Comment by kiomadoushi** [comment]
Ah I never thought to try Age of Exile mobs. Only tested with vanilla: zombies, skeletons, creepers, phantoms, spiders.

**Comment by RobertSkalko** [comment]
should be fixed
