### ISSUE TITLE
Player GUI types

### ISSUE THREAD

**Issue by Spatcholla** [RobertSkalko/Age-of-Exile#12]
What are the available player GUI types? Currently, is it set to Vanillas and was wondering if there are other types that have been implemented at this time. I am hoping to find something or edit the configuration to work well with [RPG-Hud's](https://github.com/KurodaAkira/RPG-Hud) modern style.

**Comment by RobertSkalko** [comment]
Just this one for now, and option to disable it. I don't plan to add mod specific compatibility anytime soon. But i might create different gui types.

**Comment by Spatcholla** [comment]
Thank you for your response on this and I completely understand not wanting to build in specific compatibility. I would be happy with just being able to move the mana and shield bars around. Regardless, this is an awesome mod. Thank you very much and keep up the great work!
