### ISSUE TITLE
Crash server AoE 2.1.1

### ISSUE THREAD

**Issue by Anhelm** [RobertSkalko/Age-of-Exile#122]
[crash-2021-07-17_08.27.27-server.txt](https://github.com/RobertSkalko/Age-of-Exile/files/6834293/crash-2021-07-17_08.27.27-server.txt)

**Comment by Anhelm** [comment]
Used dungeon key 125% as soon as the player enters it immediately crash

**Comment by RobertSkalko** [comment]
try new build

**Comment by Anhelm** [comment]
Work, thanks
