### ISSUE TITLE
Some Expectations for the Old Version

### ISSUE THREAD

**Issue by CCCClear** [RobertSkalko/Age-of-Exile#135]
Is it possible to make some improvements to the 1.x version on the premise that the 2.x version update is not completed?
For example, version 1.7.15 has unlabeled equipment prefixes from 2.x.
Rings and necklaces are too easily broken and disappear to be repaired in advance.
Perhaps making all items drop before they disappear, or reducing durability costs, or returning trinkets to an unbreakable state would solve this problem.
Although I know that you may not have spare time to make these, I still propose this because of my love for the mod.

**Comment by RobertSkalko** [comment]
No. I always focus on the latest version. 

But I allow people I trust to maintain an old version though if they want, because I don't have time for multiple versions.
