### ISSUE TITLE
Black Menu when using teleporter

### ISSUE THREAD

**Issue by sifmit** [RobertSkalko/Age-of-Exile#139]
Hello,

we are experiencing an issue with the teleporter. The menu does not seem to load, we only see a black screen and we can drag it around or press tab and enter to hit a cobblestone picture that is on the top left of the screen.

Here is a crash-log for all the mods we have installed on the server.
[crash-2021-09-22_15.56.01-server.txt](https://github.com/RobertSkalko/Age-of-Exile/files/7212392/crash-2021-09-22_15.56.01-server.txt)

**Comment by Ezoteric** [comment]
Dunno whats the crash about but dont see anything AOE related.

About the teleporter, u need to use a dungeon key first to unlock something, else the screen is black.
Also a reminder, if you go duo (and maybe also team as i didnt check teams yet) only the one who used the key can see the interface and the rest will also get the same black screen or his/her own made dungeon.

**Comment by sifmit** [comment]
Well like I said I onl

**Comment by sifmit** [comment]
Without teams it worked ... sorry should have read the other issues first
