### ISSUE TITLE
crash when opening the skill tree

### ISSUE THREAD

**Issue by AwwShoot** [RobertSkalko/Age-of-Exile#19]
happened consistently
I was playing on the adventure pack server during a blood moon for each crash
latest log:
[crash-2020-09-19_11.34.29-client.txt](https://github.com/RobertSkalko/Age-of-Exile/files/5250114/crash-2020-09-19_11.34.29-client.txt)

**Comment by AwwShoot** [comment]
crashes happen after the blood moon as well, but I do not crash opening the stat menu or opening the skill tree on different worlds.

**Comment by RobertSkalko** [comment]
you have older mod version. what's the server version?

**Comment by AwwShoot** [comment]
unsure, but I am using the latest version of the modpack it is for so I assume we are both on 1.3.7.
The problem seems to have been resolved by me just opening the skill tree on a singleplayer world before entering the server. Since I resolved it myself and I am a few updates behind, I'll close the issue.
