### ISSUE TITLE
Equipping an offhand item does not update AoE stats

### ISSUE THREAD

**Issue by Tigereye504** [RobertSkalko/Age-of-Exile#27]
Equipping an offhand item does not update AoE stats. For example, I have a relic shield that grants me dodge rating, armor, and various elemental resistances. Putting it on has no effect until I change some other part of my kit at which point the shield's stats are noticed and applied. Similarly, I can remove the shield once an update has occurred while retaining its stats. This is short lived as moving the hotbar cursor is enough to trigger an update, but even so it has potential for abuse such as switching the shield for a totem of undying or consumable while keeping the shield's stats.

**Comment by RobertSkalko** [comment]
will be fixed next update

**Comment by RobertSkalko** [comment]
Update out
