### ISSUE TITLE
Orb of Transutation downgrades equipment

### ISSUE THREAD

**Issue by Tigereye504** [RobertSkalko/Age-of-Exile#28]
When used on a common item, the resulting magic item invariably has much worse base stats. For example, my agate ring dropped from 17% base lightning res to 8%. This seems unlikely to be intended, as it makes using the orbs almost always a mistake.

**Comment by RobertSkalko** [comment]
Did you try it a few times? All it says is it upgrades the rarity. Everything about the item is rerolled besides the rarity.

**Comment by Tigereye504** [comment]
That would do it. I had been upgrading commons that had exceptional rolls on the assumption that it's better to imbue a well made chestplate with magic than to do the same with a hunk of armor-shaped scrap. I didn't expect the orb to be less of an upgrade so much as sacrificing the old common item to get a magic item of the same type.

I've tried a few more times on junk gear instead of on good stuff and the armor values of the output varied wildly, so it would seem it that you are right; its just a reroll.

**Comment by RobertSkalko** [comment]
Yea I think i'll eventually remake it so that it just increases rarity and all values alongside it. But i didn't yet figure out how to do it so for now it's a reroll with upgraded rarity.
