### ISSUE TITLE
Quite a few Age of Exile errors when starting server

### ISSUE THREAD

**Issue by DJTobi1Kenobi** [RobertSkalko/Age-of-Exile#29]
I get a lot of errors regarding Age of exile conditions missing. For example:

[09:03:15] [main/WARN]: mmorpg:shiver missing from registry, but requested!

[Server Log](https://pastebin.com/V1aWVShA) (I do not know why it is calling it sensitive content, I assure you it is only a server log)

**Comment by RobertSkalko** [comment]
Does it matter? Do they do anything? The errors should be normal as i deleted those effects in an update.

**Comment by DJTobi1Kenobi** [comment]
I didn't know they didn't do anything, just thought I would let you know in case you weren't aware.

**Comment by RobertSkalko** [comment]
Alright np, ye I know about them.
