### ISSUE TITLE
Can't eat apple

### ISSUE THREAD

**Issue by GuerreroCraft61** [RobertSkalko/Age-of-Exile#33]
Age of Exiles 1.7.2
Curios 0.0.8
Library 1.0.6
Fabric 1.16.3

When eat apple ~~(I don't test on other food)~~ (same on other foods, I think is problem with the mana regen effect?), the client crash (not the server)
Crash report and log: https://gist.github.com/GuerreroCraft61/51cc1939fd248e5817e6bd7cd5012042

**Comment by RobertSkalko** [comment]
Does the mod even function? I don't see any logs about my mod even loading in that log.

**Comment by GuerreroCraft61** [comment]
Log 240 (not the crash-report)

**Comment by GuerreroCraft61** [comment]
I test it only with:
Patchouli
Age Of Exile
Curios
Fabric api
Library of exile
New log: https://gist.github.com/ Line 81 (crash report) for the mods used

**Comment by GuerreroCraft61** [comment]
Okey, I delete the world and it solve. (I don't close the issue if you want solve it :c)

**Comment by RobertSkalko** [comment]
Alright
