### ISSUE TITLE
No necklace slot?

### ISSUE THREAD

**Issue by MechanosG** [RobertSkalko/Age-of-Exile#36]
So I found a necklace and was going to try and equip it.  But I can't seem to find a necklace slot.  I checked curios info, and I'm under the impression that the necklace slot would be added by Age of Exile, using Curios.  But clicking the Curios button doesn't show any additional slots.  Neither does pressing the default G key to show Curios slots.  I suspect this might be a mod conflict with the mod Inventory Tabs, but I really have no idea.

![20201101180948_1](https://user-images.githubusercontent.com/4360512/97823443-d970e680-1c6d-11eb-93ba-9ed1b875dc2f.jpg)
I was holding ctrl when I took the screenshot, so the necklace stats aren't shown.

MC 1.16.3
Age-Of-Exile-1.16.3-1.7.5.jar
curios-fabric-0.0.9-1.16.3.jar
inventorytabs-0.2.3-1.16.3.jar

**Comment by RobertSkalko** [comment]
try using older curio version, it seems they updated. ill do that in a bit

**Comment by RobertSkalko** [comment]
curio updated, this shouldn't be a problem now.

**Comment by MechanosG** [comment]
Cool, I'll give it a try.  Thanks.
