### ISSUE TITLE
[1.16.3] Salvaging station throws items out on the ground if there is something in slot one output.

### ISSUE THREAD

**Issue by ProsperCraft** [RobertSkalko/Age-of-Exile#37]
Age-Of-Exile-1.16.3-1.7.6

**Comment by RobertSkalko** [comment]
Intentional. I had some difficulties with dupes so that was the fix. If you consider it a bug you can keep the issue, i might come back to it much later when i'm done with other features.

**Comment by ProsperCraft** [comment]
I see it as a bug because when the first slot is full, it should put things in the second slot, or the third ect..

**Comment by RobertSkalko** [comment]
Salvage station was reworked in this update
