### ISSUE TITLE
A way determine max level for specific regions

### ISSUE THREAD

**Issue by XantiFuchs** [RobertSkalko/Age-of-Exile#38]
If you have a server with players that play on it there should be away to determine max level of the Mobs for the spawn region its not fun if a new player runs into an 11k HP zombie. Is there a way you might add that to a future release?

**Comment by RobertSkalko** [comment]
"there should be away to determine max level of the Mobs for the spawn region"

The max level of mobs at spawn is 1. 

I'm not understanding your issue.

**Comment by XantiFuchs** [comment]
We are using that config but what i mean is that in a for example 500 block radius around the worldspawn you can set the maximum level for monsters in this block radius

**Comment by RobertSkalko** [comment]
I can add back the min lvl area zone i guess.

**Comment by XantiFuchs** [comment]
that would be wonderfull! and helpfull for servers for modpacks like CTE Harmony

**Comment by RobertSkalko** [comment]
Overworld is now lvl 1-10 so this shouldn't be a problem anymore.
