### ISSUE TITLE
Question: Where is Magic Shield?

### ISSUE THREAD

**Issue by hagfelsh** [RobertSkalko/Age-of-Exile#40]
This isn't an issue... but I'm baffled.  Where do I find Magic Shield?  I'm getting wrecked by cave spiders and it sounds pretty handy.

**Comment by RobertSkalko** [comment]
It's a stat like health, but for mages. It's not an actual shield.

**Comment by hagfelsh** [comment]
Ohhhhh jeez.  Thanks!
