### ISSUE TITLE
[FEEDBACK] Jewelry Durability

### ISSUE THREAD

**Issue by JLDAGH** [RobertSkalko/Age-of-Exile#43]
**Is your feature request related to a problem? Please describe.**
Despite the fact that the raw durability numbers of jewelry (rings and amulet) is almost always higher than the armor pieces, jewelry loses durability much, much faster than armor. To the point where you'll repair your jewelry 6 or more times before you even need to start worrying about your regular armor, and this is while enchanted with unbreaking 3 (provided that enchantment affects jewelry, which I assume it does).

**Describe the solution you'd like**
I'd like jewelry durability buffed somewhat. The fact that its durability is hidden behind another button press in the menu makes the matter worse unfortunately. I have to remember to check its durability on a regular basis, or risk losing a good piece of gear. Hence my general preference to not wear jewelry at all. My preference would be that its durability was similar to armor, so that when you go to repair your armor, you also repair your jewelry, and you're all set for another long bit of fighting.

**Additional context**
Just seems odd that jewelry durability drops so, so much faster than armor, when armor is what is being directly hit by mobs.
NOTE: Jewelry was encountered and tested only on the Craft to Exile Harmony modpack

**Comment by RobertSkalko** [comment]
This will be tweaked in next patch, but the patch will need a few weeks at least as it's a major update.

**Comment by Tigereye504** [comment]
I did notice that jewelry is impacted by damage sources that armor is not. Not sure if that is intentional, but it leads to far, far faster degradation especially when fighting stuff like cave spiders.

**Comment by RobertSkalko** [comment]
Fixed
