### ISSUE TITLE
Questions and Feedback, if you're interested.

### ISSUE THREAD

**Issue by MechanosG** [RobertSkalko/Age-of-Exile#47]
Heya.  First off, wanna say thanks for the mod.  I'm currently testing it in a large-ish 1.16.4 modpack with AoE 1.7.7, and just started multiplayer testing.  I have questions, comments, and a minor but annoying bug to report.

1.  The level scaling based on distance from spawn.  Is this configurable?  The default scaling is..  well terrible.  In a multiplayer environment, you can expect players to spawn then set out in all directions.  But with default scaling, not even 500 distance away from spawn means enemies 1 shot you, even in a full set of vanilla equivalent armor.  ~~I would like to test reducing this scaling to about 1/10th the current amount, then go from there (so enemies seen at 500 distance are seen at 5000 distance instead).  I see some config options, but I'm not sure if any of them do specifically what I'm wanting.~~ Found the datapack config option, so I'll be testing it on my end.

2.  ~~I would like to suggest a "Character Reset" button, that doesn't cost anything to activate, but resets "everything", minus your inventory.  Many of the spells for example, do terrible damage compared to other spells, or have really bad cooldowns so their DPS really is not very useful.  Yet you start with just a handful of reset points, so you're locked in if you choose abilities you don't like or can't use.  I could make a recipe for the potion to reset all spells, but I assume it's not craftable for a reason - you'd have people using one setup early game, then switching to another later as their gear progresses, etc etc, changing intended progression.  It'd be better if players choosing to reset, reset everything.  But as it is, experimenting with the mod is kinda punishing for new players.  In Path of Exile, anytime you want to try a new build (or screw up your current one), you simply start a new character.  This no cost Character Reset button would serve the same purpose, starting from scratch.~~

3.  ~~While I'm going to test this myself with KubeJS, I suggest letting low tier gear be crafted without having to grind for loot first (with default configs, you need 2 ore of potential, which means 2 drops with only 7% drop rate - 28 mob kills if you're lucky and get the 2 recyclable gears you want, or you gotta make Newbie Gear Bags and pray to RNGesus).  The main reason I suggest this, is early game seems to be the most jarring part of this mod.  Items from vanilla (and other mods) quickly lose their effectiveness against Age of Exile leveled mobs, yet we need these mob kills to get actual age of exile gear (unless starter gear is turned on), and starting out we're likely to have nothing.  This results in early game deaths/cowering from everything, or grinding to get those first 30'ish kills, assuming you know what to do, even before you can set out and build a base/secure food/do other extreme early game MC activities.  In theory some of this might be avoided if a basic low tier set of gear can be crafted without those kill requirements.  Perhaps craftable low tier gear that can't be recycled, as to not provide unlimited recycling?~~

4.  Can specific gear be made compatible with AoE?  I noticed the config has an "auto compatible" option, along with blacklists.  Is the reverse possible?  A whitelist?  Or would I have to blacklist every single mod/item except for the ones I want to make compatible?  This might actually solve number 3 for me, if I just add some craftable gear from other mods and keep it low tier.  

_Edit:  After further testing with autoCompatibleItems, I do think this would handle my 3rd concern if I'm able to manually add some compatibility that the auto didn't detect._

5.  There's a bug on the skill tree menu where selecting a school from the top, when a selectable perk is underneath the button, will result in accidentally selecting the perk and wasting a spell point.  This is soul crushing lol.

6.  ~~Default Spell cooldowns and abilities in general seem pretty bad, when using the default level scaling and mob stat increases.  Most have cooldowns so high, they end up not useful and slapping enemies with a sword easily out damages the spells.  Is there a reason for this?  Also some spells seem like they weren't fully tested or something.  Like Magic Bomb and Arcane Comet.  Magic Bomb's timer before exploding takes so long, it's extremely difficult to hit anything with it.  And Arcane Comet requires a clear sky above the target, so it's rarely usable.  Or the Flower spells, with their low damage and 60 second cooldowns, I've never killed anything with one before.~~  _Edit: After playing with stat scaling on mobs, spells become a lot more useful once mob stats aren't over scaling to huge numbers._

**Comment by MechanosG** [comment]
Over the last couple weeks we've done more testing.  Number 2 is less of an issue than I thought, due to the smaller point potion being able to give you 5 back at a time.  Enemy scaling issues are worse than I thought though.  I ended up switching the server over to capping the level of enemies to the level of the player while I wait on a response, and around level 10-15 enemies start hitting so hard, it's 1 to 2 shotting us in full armor for our level.  I then experimented with changing the bonus stats that enemies get per level in the config, and there appears to be some sort of disconnect with the math.  Aka, if you give it a low number like 0.0001, low level enemies suddenly aren't able to hit you for more than 1 or 2 damage.  Yet around level 10 or so, enemy damage spikes and they start 1 shotting you again, like if enemy damage raises exponentially per level and at some point it doesn't matter what you give it in the configs?  Very weird behavior and I'm not sure what to do about it.  Even if you don't like my suggestions, any advice on how to make this more playable would be great.

**Comment by MechanosG** [comment]
Rebuilding my character to go full HP and full armor (only managed to get damage reduction to 30% and some random resists), I managed to get myself to survive 3-4 hits from regular mobs my level.  But I'm still getting 1 shotted by random buffed mods.  Then salt in the wound, the mob that killed me gets removed.  And since mobs pick up gear, high chance of them taking any loot from other mobs with them.  Hate to say it, but I'm throwing in the towel.

**Comment by MechanosG** [comment]
Thanks to a random redditor, I just found out about loading datapacks with KubeJS instead of per-world, and being able to copy the data folder from jars to see the existing datapack structure.  I see that a lot more of the mod is configurable this way.

**Comment by RobertSkalko** [comment]
Most of these suggestions are not useful after the big 2.0 update as balance changed a lot, closing.
