### ISSUE TITLE
Crash when used with the mod "slotlink" going from "Age of Exile 1.16.3-1.7.7" to "Age of Exile 1.16.3-1.7.10" in Adventure Pack modpack

### ISSUE THREAD

**Issue by Inewbz** [RobertSkalko/Age-of-Exile#51]
**Setup**
- Minecraft: 1.16.4
- Fabric API: 0.29.3+1.16
- slotlink: 2.2.0+1.16.4
- Age of Exile: 1.16.3-1.7.10

**Problem**
Opening the slotlink storage interface (via remote or block) instantly crashes single player and server

**Reproduction**
Opening the slotlink storage interface immediately crashes single player and server

**Remarks**
I understand this is being used in a modpack so it might be other issues compounded, but when using the older version I do not crash with slotlink. However, when using the new version, opening up the slotlink storage instantly causes a crash with an exception to do with "tickspeed" both in singleplayer and on my server.

**Comment by deirn** [comment]
It's NBT Crafting bug https://github.com/Siphalor/nbt-crafting/issues/64
