### ISSUE TITLE
new texture for guide book

### ISSUE THREAD

**Issue by CCCClear** [RobertSkalko/Age-of-Exile#54]
I‘ve drawn a texture for guide book. It was inspired by the texture of Azuna.
![book](https://user-images.githubusercontent.com/44665051/107137593-e9712400-6948-11eb-8dd7-cf9fb3f031bd.png)

**Comment by RobertSkalko** [comment]
Thanks, will use it when I figure out how to make a new item be used for patchouli guide book.
