### ISSUE TITLE
Area levels aren't working in singleplayer and server worlds

### ISSUE THREAD

**Issue by QuinnTheJungle** [RobertSkalko/Age-of-Exile#60]
I made a custom modpack that includes most of the same mods for the adventure pack modpack. However, the area levels in the overworld are bugged and are only at level 1 even 500 blocks past the spawn area. How can I fix this? Sorry I'm new to modpack creation

**Comment by mheps** [comment]
Same, I've noticed this since one of the latest releases. Overworld area + mob levels don't seem to change anymore even flying out far in creative mode and I haven't seen the area level change past 1.

**Comment by Joseph514** [comment]
Im having the same issue as well.

**Comment by mahjerion** [comment]
highly possible i broke it on latest release trying to fix something else, will fix it soon, recommend using a previous version

**Comment by Joseph514** [comment]
When can we expect it to be fixed?

**Comment by RobertSkalko** [comment]
It was fixed
