### ISSUE TITLE
Class Selection Bug in Multiplayer

### ISSUE THREAD

**Issue by Viotomix** [RobertSkalko/Age-of-Exile#67]
If you press the next or back button in the class Selection menu on multiplayer it switches to the next or previous class for a second and then goes back to the high elf, meaning you cannot select any other class than high elf.

It works fine in singleplayer.

The same thing happens when you go into the class Selection when you create a new Hero.

**Comment by guitisch** [comment]
hello me too ......

**Comment by Synthmania** [comment]
same here... please can we get help?

**Comment by RobertSkalko** [comment]
Most of these bugs are fixed in the test builds i push in my discord server. But I can't upload them to curseforge until they are completed.

**Comment by Synthmania** [comment]
> Most of these bugs are fixed in the test builds i push in my discord server. But I can't upload them to curseforge until they are completed.

Thanks A mil Mate!

**Comment by RobertSkalko** [comment]
Fixed
