### ISSUE TITLE
Health, Mana, Hunger and Level overlay dissapear when you press f3

### ISSUE THREAD

**Issue by Viotomix** [RobertSkalko/Age-of-Exile#68]
Edit: All of the bars are also Overlayed over the chat

**Comment by RobertSkalko** [comment]
F3 thing is a feature, because otherwise they hide the f3 info text

**Comment by Viotomix** [comment]
Oh my apologies I was unaware of that, is it covering the chat sometimes also intentional?

**Comment by RobertSkalko** [comment]
No. What i do is make the chat shorter when i play, so it doesnt overlap

**Comment by Viotomix** [comment]
Alright that works for me thank you!
