### ISSUE TITLE
Locked Spiritual Chests Crash the Server

### ISSUE THREAD

**Issue by Viotomix** [RobertSkalko/Age-of-Exile#72]
I'm not sure if I should be putting crashlogs in here so I'll put them in a pastebin instead
https://pastebin.com/g9RjPdEp

The player trying to open the chest did not have a key.

**Comment by Viotomix** [comment]
So does the Level up Lootbag
https://pastebin.com/egw0tyHn

**Comment by Synthmania** [comment]
same problem here please make a fix.

**Comment by AstralNomadED** [comment]
Same problem.  Server crashes in a "NoSuchMethodError" when trying to open a spirit chest without a key.

**Comment by RobertSkalko** [comment]
fixed
