### ISSUE TITLE
Color problems with the Skill Trees and Talents.

### ISSUE THREAD

**Issue by joscbarra** [RobertSkalko/Age-of-Exile#74]
I'm using Age of Exile mod v1.2.2 for Fabric on my RPG server. Skill Trees and Talents are dark and in some parts, there is a very strong green or yellow. A friend of mine said that everything looks normal. How can I make colors brighter?

![image](https://user-images.githubusercontent.com/81788208/113374186-e855e500-9342-11eb-8c58-3a861ab069c7.png)
![image](https://user-images.githubusercontent.com/81788208/113374210-f441a700-9342-11eb-827f-859c9e06c249.png)
![image](https://user-images.githubusercontent.com/81788208/113374470-96fa2580-9343-11eb-8810-0cfe89808060.png)
![image](https://user-images.githubusercontent.com/81788208/113374399-716d1c00-9343-11eb-8c4a-4ec7f9059be5.png)
This is the print that my friend sent.
![image](https://user-images.githubusercontent.com/81788208/113430381-75835300-93b0-11eb-8863-d9adb77a1ab8.png)

**Comment by RobertSkalko** [comment]
First time seing this, probably caused by another mod. Try removing mods till the gui looks normal.  You seem to be playing craft to exile, so just remove mods you added yourself to that modpack.

**Comment by joscbarra** [comment]
But as I said, we are playing on a server and using the same modpack. And to my friend, it looks normal. I don't know what happened to my being different.

This is the modpack: https://www.mediafire.com/file/7m78utfb6xkqrc9/Casada_Medieval.rar/file

**Comment by joscbarra** [comment]
The only mod different than his is Xaero's Minimap because it is a client mod.

**Comment by RobertSkalko** [comment]
This isn't caused by my mod because you're the only one who reported this, so keep removing mods till you find the culprit.
