### ISSUE TITLE
crash when loading a world

### ISSUE THREAD

**Issue by Rubyz67** [RobertSkalko/Age-of-Exile#75]
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 4/12/21 3:42 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5)
	at com.robertx22.age_of_exile.database.data.mob_affixes.MobAffix.applyStats(MobAffix.java:115)
	at com.robertx22.age_of_exile.uncommon.stat_calculation.MobStatUtils.lambda$addAffixStats$1(MobStatUtils.java:50)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.robertx22.age_of_exile.uncommon.stat_calculation.MobStatUtils.addAffixStats(MobStatUtils.java:50)
	at com.robertx22.age_of_exile.saveclasses.unit.Unit.recalculateStats(Unit.java:294)
	at com.robertx22.age_of_exile.capability.entity.EntityCap$DefaultImpl.forceRecalculateStats(EntityCap.java:492)
	at com.robertx22.age_of_exile.event_hooks.entity.OnMobSpawn.setupNewMobOnSpawn(OnMobSpawn.java:63)
	at com.robertx22.age_of_exile.event_hooks.entity.OnMobSpawn.onLoad(OnMobSpawn.java:28)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:44)
	at net.minecraft.server.world.ServerWorld.handler$ehg000$onLoadEntity(ServerWorld:11080)
	at net.minecraft.server.world.ServerWorld.loadEntityUnchecked(ServerWorld:938)
	at net.minecraft.server.world.ServerWorld.loadEntity(ServerWorld:846)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17227(ThreadedAnvilChunkStorage:635)
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_20460(ThreadedAnvilChunkStorage:611)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144)
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.executeTask(ServerChunkManager:545)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118)
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.runTask(ServerChunkManager:554)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:127)
	at net.minecraft.server.world.ServerChunkManager.getChunkBlocking(ServerChunkManager:1269)
	at net.minecraft.server.world.ServerChunkManager.getChunk(ServerChunkManager:1165)
	at net.minecraft.world.World.getChunk(World:209)
	at net.minecraft.server.world.ServerWorld.addPlayer(ServerWorld:815)
	at net.minecraft.server.world.ServerWorld.onPlayerConnected(ServerWorld:798)
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager:224)
	at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler:113)
	at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$ejp000$handlePlayerJoin(ServerLoginNetworkHandler:562)
	at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler:65)
	at net.minecraft.network.ClientConnection.tick(ClientConnection:228)
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:173)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:882)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1759421872 bytes (1677 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Suspected Mods: Fabric Lifecycle Events (v1) (fabric-lifecycle-events-v1), Age of Exile (mmorpg)
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.2.2
		alloy_forgery: Alloy Forgery 1.0.8
		amecs: Amecs 1.3.3+mc.1.16.3
		amecsapi: Amecs API 1.1.3+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		anvil_fix: AnvilFix 1.2.1-1.16
		architectury: Architectury 1.10.139
		arstheurgia: Ars Theurgia 1.0.6
		artifacts: Artifacts 3.2.0+fabric
		astromine: Astromine 1.11.5+fabric-1.16.5
		astromine-core: Astromine: Core 1.11.5+fabric-1.16.5
		astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5
		astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5
		astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5
		astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
		autobackup: Auto Backup Mod 1.4.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		backslot: BackSlot 1.1.9
		battletowers: Battle Towers 3.3.4-1.16.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		bendy-lib: Bendy api 1.1.0
		better-local-server: Better Local Server 1.1.1
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		betterend: Better End 0.9.1-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		blade: Blade 2.0.0
		blame: Blame 1.16.4-2.4.1
		blockshifter: Blockshifter 1.3.2+fabric-1.16.4
		blockus: Blockus 2.1.1+1.16.5
		blue_endless_jankson: jankson 1.2.0
		bno: Basic Nether Ores 1.16.5-5.5.0-Fabric
		byg: BYG 1.1.7
		caelus: Caelus API 0.0.15-1.16.4
		campanion: Campanion 1.3.5
		cardinal-components: Cardinal Components API 2.8.0
		cardinal-components-base: Cardinal Components API (base) 2.8.0
		cardinal-components-block: Cardinal Components API (blocks) 2.8.0
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.0
		cardinal-components-entity: Cardinal Components API (entities) 2.8.0
		cardinal-components-item: Cardinal Components API (items) 2.8.0
		cardinal-components-level: Cardinal Components API (world saves) 2.8.0
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.0
		cardinal-components-util: Cardinal Components API (utilities) 2.8.0
		cardinal-components-world: Cardinal Components API (worlds) 2.8.0
		carrier: Carrier 1.7.5
		castle_dungeons: Castle Dungeons 2.2
		cavebiomes: Cave Biomes 0.6.2
		cdsam: Survival Additions 1.3.2-Fabric-1.16.5
		chainmail: Chainmail 0.5.0
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.3
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.19
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compactstatuseffects: Compact Status Effects 1.3.0
		cosmetic-armor: Cosmetic Armor 1.0.0
		crawl: Crawl 0.8.2
		crowdin-translate: CrowdinTranslate 1.2
		curios: Curios API 0.0.13-1.16.5
		curiouselytra: Curious Elytra 1.1.1-1.16.5
		damagetilt: Damage Tilt 1.16-fabric-0.1.2
		desolation: Desolation 1.1.1
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dungeons_of_exile: Dungeons of Exile 1.1.1
		dynamicfps: Dynamic FPS 2.0.1
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		eldritch_mobs: Eldritch Mobs 1.6.8
		emotecraft: Emotecraft 2.0-b2
		enchant_giver: Enchant Giver 1.0.3
		equip: EquipZ 1.6.2
		expandedstorage: ExpandedStorage 5.6.33
		fabric: Fabric API 0.32.5+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.5+351679a77d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fallingleaves: Falling Leaves 1.5.0+1.16.5
		fastfurnace: FastFurnace 2.4
		fasttransferlib: Fast Transfer Lib 0.3.1
		fatxporbs: Fat Experience Orbs 0.0.9
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.10.218
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		gateofbabylon: Gate Of Babylon 1.4.2-1.16.5
		geckolib3: Geckolib 3.0.29
		givemehats: Give Me Hats! 1.5
		glassential: Glassential 1.16.4-1.1.5
		greater_eye: Greater Eye of Ender 1.1.5
		haema: Haema 1.6.0
		heartbond: Heartbond 1.0.0
		hellish-materials: Hellish Materials 0.12.2
		hwg: Happiness is a Warm Gun 1.0.9
		identity: Identity 1.12.0-beta-1.16.5
		illuminations: Illuminations 1.4.9
		impersonate: Impersonate 2.1.0
		indrev: Industrial Revolution 1.9.0-BETA
		inmis: Inmis 2.2.1-1.16.5
		inventory_control_tweaks: Inventory Control Tweaks 1.3.3+MC1.16.2-1.16.5
		inventorysorter: Inventory Sorter 1.7.8-1.16
		io_github_onyxstudios_cardinal-components-api: Cardinal-Components-API 2.7.9
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		lapisreserve: Lapis Reserve 1.0.6
		lchunkloader: Literally Chunk Loader 2.0.2
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		library_of_exile: Library of Exile 1.0.7
		libstructure: LibStructure 1.5
		lightstones: Lightstones 1.3.0
		lithium: Lithium 0.6.4
		magic_lanterns: Magic Lanterns 1.4.5
		magic_mirror: Magic Mirror 1.1
		magna: Magna 1.5.1-1.16.5
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		mmorpg: Age of Exile 1.7.14
		moborigins: Mob Origins 1.3.1
		mobz: MobZ 2.4.6
		modify-drops-api: Modify Drops API 0.3.1
		modmenu: Mod Menu 1.16.9
		more_gems: More Gems 1.1.22
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		mousewheelie: Mouse Wheelie 1.6.4+mc1.16.4
		multi_item_lib: Multi Item Lib 1.2.0
		mythicmetals: Mythic Metals 0.9.9
		nbtcrafting: NBT Crafting 2.0.6+mc1.16.4
		netherite_plus: Netherite Plus Mod 1.4.2-1.16.5
		notenoughcrashes: Not Enough Crashes 3.2.0
		offlineskins: OfflineSkins 1.16.5-v1-fabric
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.4
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		org_joml_joml: joml 1.10.0
		origins: Origins 0.7.0
		origins-classes: Origins: Classes 1.1.1
		oro_config: OroArmor Config 2.0.0
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 1.10.0+21w14a
		perspectivemod: Perspective Mod Redux 0.0.5
		phosphor: Phosphor 0.7.1+build.11
		piglib: Piglib 1.0.1
		playerabilitylib: Pal 1.2.1
		pling: Pling 1.3.0
		polymorph: Polymorph 0.0.10-1.16.5
		quickshulker: Quick Shulker 1.1.14-1.16
		rare-ice: Rare Ice 0.2.2
		reach-entity-attributes: Reach Entity Attributes 1.1.0
		repurposed_structures: Repurposed Structures 1.16.5-1.10.1-fabric
		requiem: Requiem 1.5.1
		requiemapi: Requiem-API 1.5.1
		respawnablepets: Respawnable Pets 1.16.5-2
		ringsofascension: Rings of Ascension 1.1.1
		roughlyenoughitems: Roughly Enough Items 5.11.202
		roughlyenoughitems-api: REI (API) 5.11.202
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.202
		roughlyenoughitems-runtime: REI (Runtime) 5.11.202
		rpgz: RPGZ 0.4.6
		sakurarosea: Sakura Rosea 1.6.0-MC1.16.3-fabric
		satin: Satin 1.5.1
		sgod: Save Gear on Death 0.0.2
		shulkerutils: shulkerutils 1.0.1-1.16
		silky_spawners: Silky Spawners 2.1.0+build.2-1.16
		simple_backpack: SimpleBackpack 1.0.38
		slotlock: SlotLock 1.0.3-BETA
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.1.0
		sodium-extra: Sodium Extra 0.2.2
		somnus: Somnus API 0.0.10-1.16.4
		spark: spark 1.5.2
		spellbound: Spellbound 1.2.1
		spruceui: SpruceUI 2.0.4+1.16
		staffofbuilding: Staff of Building 1.2.5-1.16.5
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		structure-helpers: Structure Helpers 3.0.0
		team_reborn_energy: Energy 0.1.1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		tweed: Tweed API 3.0.0-beta.22
		vanguard: Vanguard 1.0.5
		vanilla-hammers: Vanilla Hammers 3.0.2-1.16.5
		vanillaenhanced: VanillaEnhanced 1.4.0
		voyager: Voyager 1.0.0
		white_rabbit: White Rabbit 1.0.9+21w10a
		wildfire_gender: Wildfire's Gender Mod 1.5.6
		wildworld: Wild World 2.0.0+1.16.5
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		wrenchable: Wrenchable 1.0.0+1.16.1
		wthit: wthit 2.6.0
		xaerominimap: Xaero's Minimap 21.5.0
		xaeroworldmap: Xaero's World Map 1.13.1
		yungsapi: YUNG's API 1.16.5-Fabric-2
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['MysticalRuby870'/98, l='ServerLevel[:( no babeee!!!]', x=-148.52, y=33.00, z=53.69]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by mahjerion** [comment]
going to archive 1.7.14, thanks for posting. not sure what's going on and why that broke things

**Comment by Rubyz67** [comment]
it still doesnt work :(

**Comment by RobertSkalko** [comment]
at com.robertx22.age_of_exile.database.data.mob_affixes.MobAffix.applyStats(MobAffix.java:115)

null here mahj

**Comment by Rubyz67** [comment]
it might not be compatible with the new fabric api

**Comment by Rubyz67** [comment]
:(

**Comment by RobertSkalko** [comment]
Stop spamming, mahj will fix it when he gets to it.
