### ISSUE TITLE
the mod fails to launch

### ISSUE THREAD

**Issue by RealKingLobster** [RobertSkalko/Age-of-Exile#83]
whenever i try to launch the mod it says failed to launch Could not find required mod: mmorpg requires {cardinal-components-chunk @ [>=2.5.0]}  and then a 2end line saying Creating Empty clause ?

**Comment by RobertSkalko** [comment]
Click on the file you downloaded from here: https://www.curseforge.com/minecraft/mc-mods/age-of-exile/files

Look down in dependencies. Download them all.
