### ISSUE TITLE
Gear Repair Station... Bug?

### ISSUE THREAD

**Issue by DaisukeVN** [RobertSkalko/Age-of-Exile#84]
Version: Age-Of-Exile-1.16.5-1.8.0 (Discord Beta)
It's possible to insert "not" AoE-Items and ressources.
There you can waste ressources because it consume ressources without repairing the tool.

example:
Iron-Ingot + Mountaineer Pickaxe (MC-Dungeon Mod) = Consume Iron-Ingot without repairing the tool.

Maybe you should restrict it that the Station is only for AoE Items.

![2021-04-25_12 59 40](https://user-images.githubusercontent.com/4640928/115990822-a75d9300-a5c5-11eb-8c3f-edd037682056.png)

**Comment by RobertSkalko** [comment]
Fixed in next build
