### ISSUE TITLE
mmorpg:unknown_stats?

### ISSUE THREAD

**Issue by Hentilador** [RobertSkalko/Age-of-Exile#86]
I'm having a problem with items having unknown stats
![16202913132318875907019563141711](https://user-images.githubusercontent.com/59157281/117270544-e88a5880-ae8b-11eb-85d3-746fa63783cc.jpg)

**Comment by RobertSkalko** [comment]
is that the 1.8 beta version?

**Comment by Hentilador** [comment]
It is 1.7.15

**Comment by RobertSkalko** [comment]
The monster unique rarity should be from 1.8 beta, so i think you updated then downgraded.

**Comment by Hentilador** [comment]
I might have downloaded the 1.8 then removed it from the server and downloaded the 1.7.15. What do I do to fix this?

**Comment by RobertSkalko** [comment]
Nothing much, just ignore the old broken items.

**Comment by Hentilador** [comment]
so these are nothing right now?

**Comment by RobertSkalko** [comment]
Yes these are expected because 1.8 is a world breaking update due to amount of changes.
