### ISSUE TITLE
Hell1-Portal teleport into the ground without Exit-Portal

### ISSUE THREAD

**Issue by DaisukeVN** [RobertSkalko/Age-of-Exile#87]
AoE-Version: 1.8-Beta (Discord-Version)

The Hell1-Portal teleport me inside the ground without creating a portal back.
Luckily I changed gamemode to spectator fast enough to survive and make a picture.

![2021-05-09_20 18 04](https://user-images.githubusercontent.com/4640928/117582723-b125e100-b103-11eb-82cd-0883c3770fd0.png)

**Comment by RobertSkalko** [comment]
Are you sure this has nothing to do with that last issue with better nether you posted?

Also, I use a portal api for the portals.

https://github.com/kyrptonaught/customportalapi

**Comment by RobertSkalko** [comment]
I stopped using portal api and use my own teleport systems now. Closing.
