### ISSUE TITLE
Hell3 - Crashed Server after joining Hell3 (New Chunk Gen)

### ISSUE THREAD

**Issue by DaisukeVN** [RobertSkalko/Age-of-Exile#88]
**ErrorCode**
https://pastebin.com/FBKtRDYp

I know in the error it show "BetterNether"
But why did "BetterNether" try to interfere the worldGen of Age of Exile?

Should I report it to the Dev of "BetterNether"?

**Comment by RobertSkalko** [comment]
Please do, I don't see why it failed there.

**Comment by DaisukeVN** [comment]
Okay. I report it. Hopefully the devs are still activ there.
https://github.com/paulevsGitch/BetterNether/issues/346
