### ISSUE TITLE
Crash AoE 1.8.0 [miners-horizon-1.6.1-1.16.5]

### ISSUE THREAD

**Issue by Anhelm** [RobertSkalko/Age-of-Exile#89]
Mods: AoE 1.8.0
Conflicting Mod: Miners Horizon(https://www.curseforge.com/minecraft/mc-mods/miners-horizon)
Crash-log:
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 5/13/21 8:10 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.robertx22.world_of_exile.blocks.delay.TowerDeployer.placeLaddersForFloor(TowerDeployer.java:177)
	at com.robertx22.world_of_exile.blocks.delay.TowerDeployer.onTick(TowerDeployer.java:72)
	at com.robertx22.world_of_exile.blocks.delay.DelayedBlockEntity.method_16896(DelayedBlockEntity.java:46)
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.robertx22.world_of_exile.blocks.delay.TowerDeployer.placeLaddersForFloor(TowerDeployer.java:177)
	at com.robertx22.world_of_exile.blocks.delay.TowerDeployer.onTick(TowerDeployer.java:72)
	at com.robertx22.world_of_exile.blocks.delay.DelayedBlockEntity.method_16896(DelayedBlockEntity.java:46)

-- Block entity being ticked --
Details:
	Name: world_of_exile:delay // com.robertx22.world_of_exile.blocks.delay.DelayedBlockEntity
	Block: Block{world_of_exile:delay}
	Block location: World: (2120,148,2424), Chunk: (at 8,9,8 in 132,151; contains blocks 2112,0,2416 to 2127,255,2431), Region: (4,4; contains chunks 128,128 to 159,159, blocks 2048,0,2048 to 2559,255,2559)
	Block: Block{world_of_exile:delay}
	Block location: World: (2120,148,2424), Chunk: (at 8,9,8 in 132,151; contains blocks 2112,0,2416 to 2127,255,2431), Region: (4,4; contains chunks 128,128 to 159,159, blocks 2048,0,2048 to 2559,255,2559)
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:510)
	at net.minecraft.class_3218.method_18765(class_3218.java:429)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Rivkat'/278, l='ServerLevel[world]', x=2070.07, y=207.49, z=2334.91]]
	Chunk stats: ServerChunkCache: 1478
	Level dimension: minershorizon:miners_horizon
	Derived: true
	Level spawn location: World: (144,72,224), Chunk: (at 0,4,0 in 9,14; contains blocks 144,0,224 to 159,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6039470 game time, 6551810 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 129678 (now: false), thunder time: 92658 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.8.0-41-generic
	Java Version: 1.8.0_282, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 5032198624 bytes (4799 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 20 total; -Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		adorn: Adorn 1.13.0+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.2
		adventure-platform-fabric: adventure-platform-fabric 4.0.0-SNAPSHOT
		adventurez: AdventureZ 1.2.2
		alloy_forgery: Alloy Forgery 1.1.0
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		anvil_fix: AnvilFix 1.2.1-1.16
		appleskin: AppleSkin 1.0.11
		architectury: Architectury 1.12.148
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automated_crafting: Automated Crafting 1.3.21+MC1.16.2-1.16.5
		balance_of_exile: Balance of Exile 1.0.5
		bannerpp: Banner++ 2.0.2+mc.1.16.3
		battletowers: Battle Towers 3.3.4-1.16.4
		beenfo: Beenfo 1.16.5-fabric0.30.0-1.3
		besmirchment: Besmirchment 1.16.5-4
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		betterend: Better End 0.9.5-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		bewitchment: Bewitchment 1.16.5-11
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		blockus: Blockus 2.0.2+1.16.4
		blue_endless_jankson: jankson 1.2.0
		cardinal-components: Cardinal Components API 2.8.2
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-block: Cardinal Components API (blocks) 2.8.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.2
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cardinal-components-item: Cardinal Components API (items) 2.8.2
		cardinal-components-level: Cardinal Components API (world saves) 2.8.2
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.2
		cardinal-components-util: Cardinal Components API (utilities) 2.8.2
		cardinal-components-world: Cardinal Components API (worlds) 2.8.2
		chainmail: Chainmail 0.5.0
		charm: Charm 2.3.2
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cloth-api: Cloth API 1.5.50
		cloth-armor-api-v1: Cloth Armor API v1 1.5.50
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.50
		cloth-common-events-v1: Cloth Common Events v1 1.5.50
		cloth-config2: Cloth Config v4 4.11.19
		cloth-datagen-api-v1: Cloth Datagen v1 1.5.50
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.50
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.5.50
		cloth-utils-v1: Cloth Utils v1 1.5.50
		club_minnced_discord-webhooks: discord-webhooks 0.5.6
		colonies: Colonies 1.1.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		com_squareup_okhttp3_okhttp: okhttp 3.14.9
		com_squareup_okio_okio: okio 1.17.2
		com_vdurmont_emoji-java: emoji-java 5.1.1
		compressedblocks: Compressed Blocks 1.0
		crimsonmoon: Crimson Moon 2.0.4-1.16.5
		crowdin-translate: CrowdinTranslate 1.2
		curios: Curios API 0.0.11-1.16.4
		customportalapi: Custom Portals 0.0.1-beta25-1.16
		desolation: Desolation 1.1.1
		enchant_giver: Enchant Giver 1.0.3
		expandedstorage: ExpandedStorage 5.6.33
		extradoors: ExtraDoors 1.8.2-1.16.2
		fabric: Fabric API 0.33.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fasttransferlib: Fast Transfer Lib 0.3.1
		fdlink: Fabric <-> Discord Link 0.8.19
		fdlink_1_12_2: Fabric <-> Discord Link 0.8.19
		fdlink_1_15_2: Fabric <-> Discord Link 0.8.19
		fdlink_1_16: Fabric <-> Discord Link 0.8.19
		fdlink_1_7_10: Fabric <-> Discord Link 0.8.19
		fdlink_1_8_9: Fabric <-> Discord Link 0.8.19
		fdlink_common: Fabric <-> Discord Link 0.8.19
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.8
		ftbguilibrary: FTB GUI Library 1605.2.1.41
		ftbquests: FTB Quests 1605.2.1-build.39
		geckolib3: Geckolib 3.0.2
		go-fish: Go Fish 1.2.1-beta-1.16.4
		haema: Haema 1.7.0
		headshot: Headshot 1.0.6
		heartbond: Heartbond 1.0.0
		impersonate: Impersonate 2.2.0
		inmis: Inmis 2.2.1-1.16.5
		inventorysorter: Inventory Sorter 1.7.9-1.16
		itemfilters: Item Filters 1605.2.4-build.30
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 8
		kubejs: KubeJS 1605.3.7-build.190
		kyrptconfig: Kytpt Config 1.1.6-1.16
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		library_of_exile: Library of Exile 1.0.7
		libstructure: LibStructure 1.5
		lint: Lint 2.0.0-SNAPSHOT
		lithium: Lithium 0.6.4
		lootcrates: LootCrates 1.0.0
		luckperms: LuckPerms 5.3.9
		mcda: MC Dungeons Armors 1.4.2
		mcdw: MC Dungeons Weapons 3.1.2
		mcsa: MC Story Mode Armor 2.1.0
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		minecraft: Minecraft 1.16.5
		minershorizon: Miner's Horizon 1.6.1-1.16.5
		minimotd-fabric: MiniMOTD 2.0.2
		miskatonicmysteries: Miskatonic Mysteries 0.0.3
		mmorpg: Age of Exile 1.8.0
		mobz: MobZ 2.4.5
		mythicmetals: Mythic Metals 0.9.9
		nbtcrafting: NBT Crafting 2.0.6+mc1.16.4
		net_dv8tion_jda: JDA 4.2.1_255
		net_kyori_adventure-api: adventure-api 4.7.0
		net_kyori_adventure-key: adventure-key 4.7.0
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.1.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.7.0
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.7.0
		net_kyori_examination-api: examination-api 1.1.0
		net_kyori_examination-string: examination-string 1.1.0
		net_sf_trove4j_trove4j: trove4j 3.0.3
		omega-config: OmegaConfig 1.0.4
		org_apache_commons_commons-collections4: commons-collections4 4.1
		org_apache_logging_log4j_log4j-slf4j-impl: log4j-slf4j-impl 2.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		org_json_json: json 20210307
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-nop: slf4j-nop 1.7.25
		patchouli: Patchouli 1.16.4-48-FABRIC
		pehkui: Pehkui 2.1.0+21w18a
		phosphor: Phosphor 0.7.2+build.12
		playerabilitylib: Pal 1.2.1
		programmerartinjector: Programmer Art Injector 1.2.1
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		recipeconditions: Fabric Recipe Conditions 0.4.0
		rhino: Rhino 1.7.13-build.23
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		savemystronghold: Save My Stronghold! 1.16.4-1.0
		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
		somnus: Somnus API 0.0.11-1.16.5
		spawner-config: Spawner Config 1.0.1-1.16.5
		spellbound: Spellbound 1.2.1
		starry_sky: Starry Skies 1.0.10-1.16.5
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		structure-helpers: Structure Helpers 3.0.0
		team_reborn_energy: Energy 0.1.1
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		the_bumblezone: The Bumblezone - Fabric 1.16.5-2.4.2
		totemicoverhaul: Totemic Overhaul 1.1.3
		trinkets: Trinkets 2.6.7
		voyager: Voyager 1.0.0
		winged: Winged Mod 1.16.5-2.0.4
		wirelessnetworks: Wireless Networks 1.0.3
		world_blender: World Blender 1.16.5-2.1.5
		world_of_exile: World of Exile 1.2.0
		worldedit: WorldEdit 7.2.5+57d5ac9
		wthit: wthit 2.8.1
		xaerominimap: Xaero's Minimap 21.3.0
		xaeroworldmap: Xaero's World Map 1.12.0
		yungsapi: YUNG's API 1.16.5-Fabric-2
		zoob: Monster Of The Ocean Depths 3.0.0
	Player Count: 1 / 20; [class_3222['Rivkat'/278, l='ServerLevel[world]', x=2070.07, y=207.49, z=2334.91]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by RobertSkalko** [comment]
Should be fixed
