### ISSUE TITLE
Skills generate no EXP from kills

### ISSUE THREAD

**Issue by SolitaryScythe** [RobertSkalko/Age-of-Exile#9]
Version:
MC 1.16.1
Fabric Loader 0.9.1+build.205
Fabric API 0.17.0+build.386-1.16.1
Age-Of-Exile-1.16.1-1.0.7

Issue:
Magic attacks and other skills from Skill Gems do not seem to register mobs as having being hit by their user; as a result mobs that die from Skill abilities before they can be hit by a weapon die without crediting players with any EXP, making progression much harder for anyone trying to play as a mage/caster or other heavily Skill Gem-based build.

**Comment by RobertSkalko** [comment]
should be fixed, reply if not so i reopen.
