### ISSUE TITLE
Unable to increase the class level

### ISSUE THREAD

**Issue by vm3aup354** [RobertSkalko/Age-of-Exile#90]
My chosen profession is to mine minerals, but no matter whether I kill monsters or mine minerals, I can’t upgrade my level.

![2021-05-13_21 39 31](https://user-images.githubusercontent.com/84137038/118133831-da13e200-b433-11eb-9650-bf140bf78ea1.png)

**Comment by RobertSkalko** [comment]
Kill level 1 hostile mobs.
