### ISSUE TITLE
hud

### ISSUE THREAD

**Issue by eririKashiwagi** [RobertSkalko/Age-of-Exile#91]
Hi! Is it possible to disable some hud bars without disabling them all?

**Comment by RobertSkalko** [comment]
Coming only in beta version. You'll be able to disable or move any

**Comment by eririKashiwagi** [comment]
> Coming only in beta version. You'll be able to disable or move any

Okey, then how i can fix this now?
![2021-05-16_15 24 07](https://user-images.githubusercontent.com/84137738/118399123-e1b5cf80-b65b-11eb-9146-c7470f0bf5fe.png)

**Comment by RobertSkalko** [comment]
lower chat width

**Comment by eririKashiwagi** [comment]
uh.. thx
waiting the beta..

**Comment by RobertSkalko** [comment]
Beta is now on curseforge
