### ISSUE TITLE
nether and end broken (sorry for broken english)

### ISSUE THREAD

**Issue by amytori** [RobertSkalko/Age-of-Exile#92]
so i  play on age of exile harmony with a aternos server it recently auto updated to 2.2.0b
and now the nether and end portals are broken i cant get into the nether i tried everything i can stand i nthe nether portal for 15 minutes nothing happends same with the end portal.

edit: it updated from 2.0.2c  to 2.2.0b

**Comment by RobertSkalko** [comment]
This is age of exile mod, not the the craft to exile modpack. Please go here https://www.curseforge.com/minecraft/modpacks/crafttoexileharmony

**Comment by amytori** [comment]
oh F sorry!!!
